-- Расписание хранится в clients.profile.schedule (jsonb).
-- Отдельная колонка schedule не нужна — достаточно миграции profile:
-- supabase/add-client-profile.sql
--
-- Формат: { "sessions": [{ "id", "date", "time", "note" }] }
